import {User} from "../entity/User";
import {ignore} from "../type/index";

// this sourceFile was generated by processor-unit 
let map:Map<any,Array<any>>=new Map();

export function init0(): void {
    map.set(User.prototype,new Array()) 
    Object.defineProperty(User.prototype,"toJSON",{
        configurable:true,
        value:function(){
            const old:any={};
            for(let k of Object.keys(this))
                old[k]=this[k]
            for (let k of map.get(User.prototype)||[])
                old[k[1]]=k[2].bind(this)((this as any)[k[0]]);
            return old;
        }
    })
    map.get(User.prototype)?.push(["password","password",ignore] )
}
