import {Media} from "../entity/Media";
import {ignore} from "../type/index";

// this sourceFile was generated by processor-unit 
let map:Map<any,Array<any>>=new Map();

export function init0(): void {
    map.set(Media.prototype,new Array()) 
    Object.defineProperty(Media.prototype,"toJSON",{
        configurable:true,
        value:function(){
            const old:any={};
            for(let k of Object.keys(this))
                old[k]=this[k]
            for (let k of map.get(Media.prototype)||[])
                old[k[1]]=k[2].bind(this)((this as any)[k[0]]);
            return old;
        }
    })
    map.get(Media.prototype)?.push(["event","event",ignore] )
}
